
Set training year
```{r}
year<-2014
```


Pull seed data and tourney results
```{r}

library(stringr)
library(tidyverse)
library(magrittr)
library(dplyr)

# load data need data files Seeds, Results, Conferences, and Coaches
seeds <- read.csv("data/NCAATourneySeeds.csv")
seeds<-subset(seeds,Season==year)
results <- read.csv("data/RegularSeasonCompactResults.csv")
results<-subset(results,Season==year)
testData<-read.csv("data/NCAATourneyCompactResults.csv")
testData<-subset(testData,Season==year)
```

Strip seed text (!!!)
```{r}
# Remove characters from seed so integer remains
seeds$Seed <- as.integer(str_extract_all(seeds$Seed, "[0-9]+"))
seedsEX<-seeds
head(seeds) # check to make sure regional characters are removed
```

Strip regualr season results data (!!!)
```{r}
# Keep only the needed files from the results; Season, WTeamID, and LTeamID
resultsEX<-results
resultsEX %<>% select(Season, WTeamID, LTeamID)
# Rearrange data so it matches submission file
resultsEX %<>% mutate(team_id_diff = WTeamID - LTeamID, 
                    Team1 = case_when(team_id_diff < 0 ~ WTeamID,
                                      team_id_diff > 0 ~ LTeamID),
                    Team2 = case_when(team_id_diff > 0 ~ WTeamID,
                                      team_id_diff < 0 ~ LTeamID),
                    result = if_else(WTeamID == Team1, 1, 0))
resultsEX %>% filter((Team1 - Team2) > 0)
#Note on the above, if winner ID is greater than loser ID then Team 1 is loser. If loser ID is greater than winner, then Team 1 is the winner. Opposite for Team 2. This approximates random / uniform distribution.

# Remove WTeamID, LTeamID, and team_id_diff
resultsEX %<>% select(1,5:7)
resultsEX
```

Strip Test data (!!!)
```{r}
# Keep only the needed files from the results; Season, WTeamID, and LTeamID
testDataEX<-testData
testDataEX %<>% select(Season, WTeamID, LTeamID)
# Rearrange data so it matches submission file
testDataEX %<>% mutate(team_id_diff = WTeamID - LTeamID, 
                    Team1 = case_when(team_id_diff < 0 ~ WTeamID,
                                      team_id_diff > 0 ~ LTeamID),
                    Team2 = case_when(team_id_diff > 0 ~ WTeamID,
                                      team_id_diff < 0 ~ LTeamID),
                    result = if_else(WTeamID == Team1, 1, 0))
testDataEX %>% filter((Team1 - Team2) > 0)
#Note on the above, if winner ID is greater than loser ID then Team 1 is loser. If loser ID is greater than winner, then Team 1 is the winner. Opposite for Team 2. This approximates random / uniform distribution.

# Remove WTeamID, LTeamID, and team_id_diff
testDataEX %<>% select(1,5:7)
testDataEX
```

Merge seed data into regular season results dataframe & create seed difference variable
```{r}
resultsEX$Team1Seed <- seedsEX$Seed[match(resultsEX$Team1, seedsEX$TeamID)]
resultsEX$Team2Seed <- seedsEX$Seed[match(resultsEX$Team2, seedsEX$TeamID)]
resultsEX$seedDiff<-resultsEX$Team1Seed - resultsEX$Team2Seed
resultsEX<-subset(resultsEX,!(is.na(seedDiff)))
#resultsEX$Team1Seed<-as.factor(resultsEX$Team1Seed)
#resultsEX$Team2Seed<-as.factor(resultsEX$Team2Seed)
resultsEX
```

Repeat merge for testing set dataframe
```{r}
testDataEX$Team1Seed <- seedsEX$Seed[match(testDataEX$Team1, seedsEX$TeamID)]
testDataEX$Team2Seed <- seedsEX$Seed[match(testDataEX$Team2, seedsEX$TeamID)]
testDataEX$seedDiff<-testDataEX$Team1Seed - testDataEX$Team2Seed
testDataEX<-subset(testDataEX,!(is.na(seedDiff)))
#testDataEX$Team1Seed<-as.factor(testDataEX$Team1Seed)
#testDataEX$Team2Seed<-as.factor(testDataEX$Team2Seed)
testDataEX
```

Fit logistic regression to results data
```{r}
logitModel<-glm(result~seedDiff,data=resultsEX,family=binomial(link="logit"))
summary(logitModel)
```

Predict results for NCAA tournament & output submission CSV
```{r}
NCAAPredictions<-predict(logitModel,testDataEX,type="response")
head(testDataEX)
outputFrame<-testDataEX[0]
outputFrame$ID<-paste(testDataEX$Season,testDataEX$Team1,testDataEX$Team2,sep ="_")
outputFrame$Pred<-NCAAPredictions
head(outputFrame)

write.csv(outputFrame,"Simon-testOutput.csv")
```




