
Set testing year
```{r}
year<-1987
```


Pull seed data and tourney results
```{r}

library(stringr)
library(tidyverse)
library(magrittr)
library(dplyr)

# load data need data files Seeds, Results, Conferences, and Coaches
seeds <- read.csv("data/NCAATourneySeeds.csv")
results <- read.csv("data/RegularSeasonCompactResults.csv")
results<-subset(results,Season<year)
testData<-read.csv("data/SampleSubmissionStage1.csv")
```

```{r}
# seeds <- read.csv("./data/NCAATourneySeeds.csv")
# seeds<-subset(seeds,Season<year)
# results <- read.csv("./data/RegularSeasonCompactResults.csv")
# results<-subset(results,Season<year)
# 
# for (i in 1:length(seeds$TeamID)){
#   WinCount<-0
#   for(j in 1:length(results$WTeamID)){
#     if(results$WTeamID[j]==seeds$TeamID[i]&results$Season[j]==seeds$Season[i]){
#       WinCount<-WinCount+1
#     }
#   }
#   seeds$WinCount[i]<-WinCount
# }
# 
# seeds
```


Strip seed text (!!!)
```{r}
# Remove characters from seed so integer remains
seeds$Seed <- as.integer(str_extract_all(seeds$Seed, "[0-9]+"))

seedsEX<-seeds
head(seeds) # check to make sure regional characters are removed
```

Strip regualr season results + merge in seed data
```{r}
# Keep only the needed files from the results; Season, WTeamID, and LTeamID
resultsEX<-results
resultsEX %<>% select(Season, WTeamID, LTeamID)
# Rearrange data so it matches submission file
resultsEX %<>% mutate(team_id_diff = WTeamID - LTeamID, 
                    Team1 = case_when(team_id_diff < 0 ~ WTeamID,
                                      team_id_diff > 0 ~ LTeamID),
                    Team2 = case_when(team_id_diff > 0 ~ WTeamID,
                                      team_id_diff < 0 ~ LTeamID),
                    result = if_else(WTeamID == Team1, 1, 0))
resultsEX %>% filter((Team1 - Team2) > 0)
#Note on the above, if winner ID is greater than loser ID then Team 1 is loser. If loser ID is greater than winner, then Team 1 is the winner. Opposite for Team 2. This approximates random / uniform distribution.

# Remove WTeamID, LTeamID, and team_id_diff
resultsEX %<>% select(1,5:7)
resultsEX

team1_seeds <- seeds %>% set_colnames(c("Season", "T1Seed", "Team1ID"))
team2_seeds <- seeds %>% set_colnames(c("Season", "T2Seed", "Team2ID"))

# Join seeds to training set
resultsEX %<>% left_join(., team1_seeds, by = c("Season", "Team1"="Team1ID"))
resultsEX %<>% left_join(., team2_seeds, by = c("Season", "Team2"="Team2ID"))

# Create relative round indicator 
resultsEX %<>% mutate(team1_seed_str = if_else(T1Seed < 9, 1,0),
                  team2_seed_str = if_else(T2Seed < 9, 1,0))
head(resultsEX)

# Create variable seed_diff
resultsEX %<>% mutate(seed_diff = T1Seed - T2Seed)
```

Strip Test data (!!!)
```{r}

testDataEX<-testData
testDataEX %<>% select(ID) %>% separate(ID, sep = "_", into = c("Season", "Team1", "Team2"), convert = TRUE)
head(testDataEX)

team1_seeds2 <- seeds %>% set_colnames(c("Season", "T1Seed", "Team1ID"))
team2_seeds2 <- seeds %>% set_colnames(c("Season", "T2Seed", "Team2ID"))

testDataEX %<>% left_join(., team1_seeds2, by = c("Season", "Team1"="Team1ID"))
testDataEX %<>% left_join(., team2_seeds2, by = c("Season", "Team2"="Team2ID"))
head(testDataEX)

testDataEX %<>% mutate(team1_seed_str = if_else(T1Seed < 9, 1,0),
                  team2_seed_str = if_else(T2Seed < 9, 1,0),
                  seed_diff = T1Seed - T2Seed)

                  
head(testDataEX)

```

Fit logistic regression to results data
```{r}
logitModel<-glm(result~seed_diff+team1_seed_str+team2_seed_str,data=resultsEX,family=binomial(link="logit"))
summary(logitModel)
```

Predict results & create submission file
```{r}
NCAAPredictions<-predict(logitModel,testDataEX,type="response")
head(testDataEX)
outputFrame<-testDataEX[0]
outputFrame$ID<-paste(testDataEX$Season,testDataEX$Team1,testDataEX$Team2,sep ="_")
outputFrame$Pred<-NCAAPredictions
head(outputFrame)

write.csv(outputFrame,"testOutput.csv")
```



Coach Data
```{r}

library(dplyr)

CoachData<-read.csv("data/TeamCoaches.csv")
CoachData<-subset(CoachData,LastDayNum==154)
#CoachData

CoachData %<>%
  group_by(CoachName) %>%
  mutate(CoachYears = 1:n())
CoachData


WinLossData<-read.csv("data/allteams-allseason-winloss-1985-2017.csv")
WinLossData
  
library(dplyr)
WinLossData %<>% left_join(.,select(CoachData,-c(FirstDayNum,LastDayNum)), by = c("Season", "TeamID"))
WinLossData

WinLossData$SumofWinPer <- ave(WinLossData$WinPer,WinLossData$CoachName,FUN=cumsum)
WinLossData

WinLossData$CoachWinPer<-WinLossData$SumofWinPer/WinLossData$CoachYears
WinLossData


```
Write Win/Loss Data with Coach Record into CSV
```{r}
write.csv(WinLossData, file = "allteams-allseason-allcoaches-winloss.csv", row.names = FALSE)
```



