---
title: "R Notebook"
output: html_notebook
---

```{r}
#Load libraries
library(dplyr)
```

```{r}
#Load in the data 
seasonResults <- read.csv("data/RegularSeasonDetailedResults.csv", header = TRUE)
head(seasonResults)
```


```{r}
#change the column names so that they are identical for merging
names(seasonResults) <- gsub(x = names(seasonResults), pattern = "WTeam", replacement = "Team")
names(seasonResults) <- gsub(x = names(seasonResults), pattern = "LTeam", replacement = "Team")
names(seasonResults) <- gsub(x = names(seasonResults), pattern = "W", replacement = "")
names(seasonResults) <- gsub(x = names(seasonResults), pattern = "L", replacement = "")

#combine WTeam and LTeam stats
seasonResultsCompiled <- bind_rows(seasonResults[,c(1,3:4,9:21)],seasonResults[,c(1,5:6,22:34)])
head(seasonResultsCompiled)
```


```{r}
#find all unique values by BOTH Season and TeamID
#this will be the skeleton of the final database we want
seasonResultsCompiledUnique <- distinct(seasonResultsCompiled,Season, TeamID, .keep_all = TRUE)

#loop through all the unique values
for (i in 1:NROW(seasonResultsCompiledUnique)){
    
    #we want to replace the per game data in each row of the unique data frame with averages for that team in that season
    #first filter the FULL season results by two variables, the current row SEASON and TEAM ID
    #then only select the rows where an average can be computed
    #compute the average of the filtered and selected 14 columns and insert those 14 rows into the respective row of the unique data frame
    seasonResultsCompiledUnique[i,c(3:16)] <- colMeans(seasonResultsCompiled %>%
      filter(Season == seasonResultsCompiledUnique[i,1], TeamID == seasonResultsCompiledUnique[i,2]) %>%
      select(-(Season:TeamID)))
}
```


```{r}
#write to file
write.csv(seasonResultsCompiledUnique, file = "compiled-features/allteams-allseason-averages.csv", row.names = FALSE)
```
















